//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.27 at 03:09:06 오후 KST 
//

package com.skplanet.storeplatform.sac.display.feature.appCodi.vo;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for conditionValuesType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="conditionValuesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="conditionValue" type="{http://isf.sktelecom.com/schema/tstore-request}conditionValueType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
/**
 * 
 * ISF Value Object
 * 
 * Updated on : 2014. 1. 27. Updated by : 윤주영, SK 플래닛.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "conditionValuesType", namespace = "http://isf.sktelecom.com/schema/tstore-request", propOrder = { "conditionValue" })
public class ConditionValuesType {

	@XmlElement(required = true)
	protected List<ConditionValueType> conditionValue;

	/**
	 * Gets the value of the conditionValue property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the conditionValue property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getConditionValue().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link ConditionValueType }
	 * 
	 * 
	 */
	public List<ConditionValueType> getConditionValue() {
		if (this.conditionValue == null) {
			this.conditionValue = new ArrayList<ConditionValueType>();
		}
		return this.conditionValue;
	}

	public void setConditionValue(List<ConditionValueType> conditionValue) {
		this.conditionValue = conditionValue;
	}

	public void addConditionValue(ConditionValueType condition) {
		if (this.conditionValue == null) {
			this.conditionValue = new ArrayList<ConditionValueType>();
		}
		this.conditionValue.add(condition);
	}

}
