//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.27 at 03:09:06 오후 KST 
//

package com.skplanet.storeplatform.sac.display.feature.appCodi.vo;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for multiValueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="multiValueType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="value" type="{http://isf.sktelecom.com/schema/tstore-response}valueType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cateCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="score" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="reasonCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="reason" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="relId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="order" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
/**
 * 
 * ISF Value Object
 * 
 * Updated on : 2014. 1. 27. Updated by : 윤주영, SK 플래닛.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "multiValueType", propOrder = { "value" })
public class MultiValueType {

	protected List<ValueType> value;
	@XmlAttribute(name = "id", required = true)
	protected String id;
	@XmlAttribute(name = "cateCode")
	protected String cateCode;
	@XmlAttribute(name = "score")
	protected Integer score;
	@XmlAttribute(name = "reasonCode")
	protected String reasonCode;
	@XmlAttribute(name = "reason")
	protected String reason;
	@XmlAttribute(name = "relId")
	protected String relId;
	@XmlAttribute(name = "order")
	protected Integer order;

	/**
	 * Gets the value of the value property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the value property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getValue().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link ValueType }
	 * 
	 * 
	 */
	public List<ValueType> getValue() {
		if (this.value == null) {
			this.value = new ArrayList<ValueType>();
		}
		return this.value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value) {
		this.id = value;
	}

	/**
	 * Gets the value of the cateCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCateCode() {
		return this.cateCode;
	}

	/**
	 * Sets the value of the cateCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCateCode(String value) {
		this.cateCode = value;
	}

	/**
	 * Gets the value of the score property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getScore() {
		return this.score;
	}

	/**
	 * Sets the value of the score property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setScore(Integer value) {
		this.score = value;
	}

	/**
	 * Gets the value of the reasonCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getReasonCode() {
		return this.reasonCode;
	}

	/**
	 * Sets the value of the reasonCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setReasonCode(String value) {
		this.reasonCode = value;
	}

	/**
	 * Gets the value of the reason property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getReason() {
		return this.reason;
	}

	/**
	 * Sets the value of the reason property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setReason(String value) {
		this.reason = value;
	}

	/**
	 * Gets the value of the relId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRelId() {
		return this.relId;
	}

	/**
	 * Sets the value of the relId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRelId(String value) {
		this.relId = value;
	}

	/**
	 * Gets the value of the order property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getOrder() {
		return this.order;
	}

	/**
	 * Sets the value of the order property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setOrder(Integer value) {
		this.order = value;
	}

}
