//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.27 at 03:09:06 오후 KST 
//

package com.skplanet.storeplatform.sac.display.feature.appCodi.vo;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for multiValuesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="multiValuesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="multiValue" type="{http://isf.sktelecom.com/schema/tstore-response}multiValueType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="count" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
/**
 * 
 * ISF Value Object
 * 
 * Updated on : 2014. 1. 27. Updated by : 윤주영, SK 플래닛.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "multiValuesType", propOrder = { "multiValue" })
public class MultiValuesType {

	@XmlElement(required = true)
	protected List<MultiValueType> multiValue;
	@XmlAttribute(name = "name")
	protected String name;
	@XmlAttribute(name = "count", required = true)
	protected int count;

	/**
	 * Gets the value of the multiValue property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the multiValue property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getMultiValue().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link MultiValueType }
	 * 
	 * 
	 */
	public List<MultiValueType> getMultiValue() {
		if (this.multiValue == null) {
			this.multiValue = new ArrayList<MultiValueType>();
		}
		return this.multiValue;
	}

	public void setMultiValue(List<MultiValueType> multiValue) {
		this.multiValue = multiValue;
	}

	public void addMultiValue(MultiValueType multiValue) {
		if (this.multiValue == null) {
			this.multiValue = new ArrayList<MultiValueType>();
		}
		this.multiValue.add(multiValue);
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the count property.
	 * 
	 */
	public int getCount() {
		return this.count;
	}

	/**
	 * Sets the value of the count property.
	 * 
	 */
	public void setCount(int value) {
		this.count = value;
	}

}
