//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.27 at 03:09:06 오후 KST 
//
/**
 * 
 * ISF Value Object
 * 
 * Updated on : 2014. 1. 27. Updated by : 윤주영, SK 플래닛.
 */
@javax.xml.bind.annotation.XmlSchema(namespace = "http://isf.sktelecom.com/schema/tstore-response", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.UNQUALIFIED)
package com.skplanet.storeplatform.sac.display.feature.appCodi.vo;

