//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.27 at 03:09:06 오후 KST 
//

package com.skplanet.storeplatform.sac.display.feature.appCodi.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for propsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="propsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="singleValues" type="{http://isf.sktelecom.com/schema/tstore-response}singleValuesType" minOccurs="0"/>
 *         &lt;element name="multiValues" type="{http://isf.sktelecom.com/schema/tstore-response}multiValuesType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="count" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
/**
 * 
 * ISF Value Object
 * 
 * Updated on : 2014. 1. 27. Updated by : 윤주영, SK 플래닛.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "propsType", propOrder = { "singleValues", "multiValues" })
public class PropsType {

	protected SingleValuesType singleValues;
	protected MultiValuesType multiValues;
	@XmlAttribute(name = "count", required = true)
	protected int count;

	/**
	 * Gets the value of the singleValues property.
	 * 
	 * @return possible object is {@link SingleValuesType }
	 * 
	 */
	public SingleValuesType getSingleValues() {
		return this.singleValues;
	}

	/**
	 * Sets the value of the singleValues property.
	 * 
	 * @param value
	 *            allowed object is {@link SingleValuesType }
	 * 
	 */
	public void setSingleValues(SingleValuesType value) {
		this.singleValues = value;
	}

	/**
	 * Gets the value of the multiValues property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the multiValues property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getMultiValues().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link MultiValuesType }
	 * 
	 * 
	 */
	public MultiValuesType getMultiValues() {
		return this.multiValues;
	}

	public void setMultiValues(MultiValuesType multiValues) {
		this.multiValues = multiValues;
	}

	/**
	 * Gets the value of the count property.
	 * 
	 */
	public int getCount() {
		return this.count;
	}

	/**
	 * Sets the value of the count property.
	 * 
	 */
	public void setCount(int value) {
		this.count = value;
	}

}
