//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.27 at 03:09:06 오후 KST 
//

package com.skplanet.storeplatform.sac.display.feature.appCodi.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.skplanet.storeplatform.framework.core.common.vo.CommonInfo;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="service">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="chCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="mbn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mdn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="conditionValues" type="{http://isf.sktelecom.com/schema/tstore-request}conditionValuesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
/**
 * 
 * ISF Value Object
 * 
 * Updated on : 2014. 1. 27. Updated by : 윤주영, SK 플래닛.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "service", "mbn", "mdn", "conditionValues" })
@XmlRootElement(name = "request", namespace = "http://isf.sktelecom.com/schema/tstore-request")
public class Request extends CommonInfo {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2108833098747902607L;

	@XmlAttribute(name = "xmlns:xsi")
	protected final String xmlnsXsi = "http://www.w3.org/2001/XMLSchema-instance";

	@XmlElement(namespace = "http://isf.sktelecom.com/schema/tstore-request", required = true)
	protected Request.Service service;
	@XmlElement(namespace = "http://isf.sktelecom.com/schema/tstore-request", required = true)
	protected String mbn;
	@XmlElement(namespace = "http://isf.sktelecom.com/schema/tstore-request")
	protected String mdn;
	@XmlElement(namespace = "http://isf.sktelecom.com/schema/tstore-request")
	protected ConditionValuesType conditionValues;

	@XmlAttribute(name = "xsi:schemaLocation")
	protected final String xsiSchemaLocation = "http://isf.sktelecom.com/schema/tstore-request.xsd";

	/**
	 * Gets the value of the service property.
	 * 
	 * @return possible object is {@link Request.Service }
	 * 
	 */
	public Request.Service getService() {
		return this.service;
	}

	/**
	 * Sets the value of the service property.
	 * 
	 * @param value
	 *            allowed object is {@link Request.Service }
	 * 
	 */
	public void setService(Request.Service value) {
		this.service = value;
	}

	/**
	 * Gets the value of the mbn property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMbn() {
		return this.mbn;
	}

	/**
	 * Sets the value of the mbn property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMbn(String value) {
		this.mbn = value;
	}

	/**
	 * Gets the value of the mdn property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMdn() {
		return this.mdn;
	}

	/**
	 * Sets the value of the mdn property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMdn(String value) {
		this.mdn = value;
	}

	/**
	 * Gets the value of the conditionValues property.
	 * 
	 * @return possible object is {@link ConditionValuesType }
	 * 
	 */
	public ConditionValuesType getConditionValues() {
		return this.conditionValues;
	}

	/**
	 * Sets the value of the conditionValues property.
	 * 
	 * @param value
	 *            allowed object is {@link ConditionValuesType }
	 * 
	 */
	public void setConditionValues(ConditionValuesType value) {
		this.conditionValues = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *       &lt;attribute name="chCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "")
	public static class Service {

		@XmlAttribute(name = "id", required = true)
		protected String id;
		@XmlAttribute(name = "chCode", required = true)
		protected String chCode;

		/**
		 * Gets the value of the id property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getId() {
			return this.id;
		}

		/**
		 * Sets the value of the id property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setId(String value) {
			this.id = value;
		}

		/**
		 * Gets the value of the chCode property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getChCode() {
			return this.chCode;
		}

		/**
		 * Sets the value of the chCode property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setChCode(String value) {
			this.chCode = value;
		}

	}

}
